const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http');
const S=require('../src/ai-session.js'),{analyze}=require('../server/deepseek.cjs'),{createServer}=require('../server.cjs');
const q={id:'q_goal',title:'希望完成什么？',why:'决定主要结果',required:true,options:[{label:'记录练习',consequence:'保存和查看练习记录'},{label:'练习反馈',consequence:'提交练习并获得反馈'}],dependsOn:['intent']};
const c={id:'c_scope',label:'限制',value:'不要登录',quote:'不要登录',sourceRef:'intent',dependsOn:['intent']};
const result=(ready=false)=>({summary:'做一个无需登录的学习工具。',candidates:[c],questions:[q],readiness:{ready,reason:ready?'关键内容已明确':'核心任务待确认'},warnings:[]});
const meta={model:'test-model',requestId:'mock-request',receivedAt:'2026-09-26T08:00:00Z'};
function first(){const s=S.fresh('雅思工具，不要登录');return S.apply(s,result(),meta,S.signature(s));}
function ready(){let s=first();s=S.decide(s,'c_scope','accepted');s=S.answer(s,'q_goal','记录练习');return S.apply(s,{...result(true),candidates:[],questions:[]},meta,S.signature(s));}
test('model cannot confirm candidates or skip unknown required answers',()=>{let s=first();assert.equal(s.decision.c_scope,'pending');s=S.answer(s,'q_goal','不确定');s=S.decide(s,'c_scope','accepted');s=S.apply(s,{...result(true),candidates:[],questions:[]},meta,S.signature(s));assert.equal(s.answers.q_goal.status,'pending');assert.throws(()=>S.confirm(s));});
test('missing evidence and fabricated source references are rejected',()=>{const s=S.fresh('不要登录');let r=result();r.candidates=[{...c,quote:'不用支付'}];assert.throws(()=>S.validateAnalysis(r,s));r=result();r.candidates=[{...c,sourceRef:'q_missing'}];assert.throws(()=>S.validateAnalysis(r,s));});
test('model-added confirmed flags never count as user consent',()=>{const s=S.fresh('不要登录');const r=result(true);r.candidates[0]={...c,status:'accepted'};const n=S.apply(s,r,meta,S.signature(s));assert.equal(n.decision.c_scope,'pending');assert.throws(()=>S.confirm(n));});
test('changed answers invalidate readiness until a fresh assessment',()=>{let s=S.confirm(ready());const snapshot=JSON.stringify(s.history[0]);s=S.answer(s,'q_goal','练习反馈');assert.equal(s.activeRevision,null);assert.ok(S.blockers(s).some(x=>x.includes('再检查')));assert.equal(JSON.stringify(s.history[0]),snapshot);assert.throws(()=>S.confirm(s));});
test('late analysis responses cannot overwrite newer input',()=>{let s=first(),sig=S.signature(s);s=S.answer(s,'q_goal','记录练习');assert.throws(()=>S.apply(s,result(),meta,sig));});
test('immutable question definitions cannot be silently rewritten by model',()=>{const s=first(),r=result();r.questions=[{...q,title:'新的问题'}];assert.throws(()=>S.validateAnalysis(r,s));});
test('changing source answers invalidates accepted dependent facts and prevents obsolete evidence acceptance',()=>{let s=first();s=S.answer(s,'q_goal','记录练习');const fact={id:'c_feature',label:'核心功能',value:'记录练习',quote:'记录练习',sourceRef:'q_goal',dependsOn:['q_goal']};s=S.apply(s,{...result(),candidates:[fact],questions:[]},meta,S.signature(s));s=S.decide(s,'c_feature','accepted');s=S.answer(s,'q_goal','练习反馈');assert.equal(s.decision.c_feature,'pending');assert.throws(()=>S.decide(s,'c_feature','accepted'));});
test('cycles and invalid dependency references are rejected',()=>{const s=S.fresh('不要登录'),r=result();r.candidates=[{...c,dependsOn:['q_goal']}];r.questions=[{...q,dependsOn:['c_scope']}];assert.throws(()=>S.validateAnalysis(r,s));});
test('confirmed exports and restored snapshots retain consent and model provenance',()=>{let s=S.confirm(ready());assert.equal(s.activeRevision,1);const p=S.specification(s);assert.equal(p.model.requestId,'mock-request');assert.equal(p.candidates[0].status,'accepted');assert.ok(S.markdown(s).includes('不要登录'));assert.deepEqual(S.restore(JSON.stringify(s)),s);assert.deepEqual(S.restore('{broken'),S.fresh());});
test('DeepSeek transport uses official URL, JSON mode, bearer key; ignores reasoning and extra fields',async()=>{let sent;const fake=async(url,opts)=>{sent={url,opts};return {ok:true,text:async()=>JSON.stringify({id:'fixture-id',choices:[{finish_reason:'stop',message:{content:JSON.stringify(result()),reasoning_content:'not consumed'}}],usage:{total_tokens:123}})};};const r=await analyze(S.input(S.fresh('不要登录')),{key:'test-only-key',model:'deepseek-flash'},fake);assert.equal(sent.url,'https://api.deepseek.com/chat/completions');assert.equal(sent.opts.headers.Authorization,'Bearer test-only-key');const body=JSON.parse(sent.opts.body);assert.equal(body.response_format.type,'json_object');assert.equal(body.thinking.type,'disabled');assert.equal(r.meta.usage.total_tokens,123);assert.ok(!JSON.stringify(r).includes('test-only-key'));});
test('empty, truncated, malformed model output and missing key never produce fake success',async()=>{const input=S.input(S.fresh('不要登录'));await assert.rejects(()=>analyze(input,{key:''}));for(const [finish,content] of [['stop',''],['length','{}'],['stop','not json']])await assert.rejects(()=>analyze(input,{key:'test-only-key'},async()=>({ok:true,text:async()=>JSON.stringify({choices:[{finish_reason:finish,message:{content}}]})})));});
test('API authentication errors are sanitized without echoing provider response or key',async()=>{await assert.rejects(()=>analyze(S.input(S.fresh('不要登录')),{key:'never-return-this'},async()=>({ok:false,status:401,text:async()=>'never-return-this'})),e=>e.message.includes('密钥无效')&&!e.message.includes('never-return-this'));});
test('local server denies cross-origin calls and private files while accepting valid JSON',async()=>{
 const server=createServer({key:'test-only-key',model:'fixture'},async payload=>({analysis:result(),meta}));await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const base='http://127.0.0.1:'+server.address().port;
 try{
  const status=await (await fetch(base+'/api/status')).json();assert.equal(status.configured,true);assert.ok(!JSON.stringify(status).includes('test-only-key'));
  for(const p of ['/.env','/server/config.cjs','/docs/CODEX_CHANGES.patch','/src/../.env'])assert.equal((await fetch(base+p)).status,404);
  const body=JSON.stringify(S.input(S.fresh('不要登录')));
  assert.equal((await fetch(base+'/api/clarify',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://example.com','X-IntentConfirm':'1'},body})).status,403);
  assert.equal((await fetch(base+'/api/clarify',{method:'POST',headers:{'Content-Type':'application/json',Origin:base,'X-IntentConfirm':'1'},body})).status,200);
 }finally{await new Promise(r=>server.close(r));}
});
test('server can be started with no key without making any model call',async()=>{let called=false;const server=createServer({key:'',model:'fixture'},async()=>{called=true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;try{const r=await fetch(base+'/api/clarify',{method:'POST',headers:{'Content-Type':'application/json',Origin:base,'X-IntentConfirm':'1'},body:'{}'});assert.equal(r.status,503);assert.equal(called,false);}finally{await new Promise(r=>server.close(r));}});
