/* DeepSeek interface; offline workflow remains independently available. */
(()=>{
 'use strict';
 const A=window.IntentAISession,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const key='intentconfirm-deepseek-v1';let session=A.fresh();try{session=A.restore(localStorage.getItem(key));}catch{}
 let active=location.protocol==='http:',step=session.intent?1:0,busy=false,error='',config={configured:false,model:'',loaded:false},batch=[],drafts={},controller=null,epoch=0;
 const select=$('#engine-select');select.value=active?'deepseek':'rules';
 function save(){try{localStorage.setItem(key,JSON.stringify(session));}catch{error='浏览器无法保存，请及时导出需求文件。';}}
 function badge(status){return `<span class="badge ${['pending','stale'].includes(status)?status:''}">${esc({accepted:'已采纳',rejected:'未采纳',pending:'待确定',confirmed:'已选择',stale:'需重新确认',excluded:'不适用'}[status]||'待确定')}</span>`;}
 function pendingQs(){return session.questions.filter(q=>!['confirmed','excluded'].includes(session.answers[q.id]?.status));}
 function dataDownload(text,extension){const url=URL.createObjectURL(new Blob([text],{type:extension==='json'?'application/json':'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='intentconfirm-deepseek-'+(session.activeRevision?'v'+session.activeRevision:'draft')+'.'+extension;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function connectionNote(){if(location.protocol!=='http:')return '<div class="notice">在线模式需要本地服务。请在项目终端运行 <code>npm run setup</code> 配置密钥，再运行 <code>npm start</code>，通过显示的本机网址打开。</div>';if(!config.loaded)return '<div class="notice">正在检查本地服务配置……</div>';if(!config.configured)return '<div class="notice">DeepSeek API Key 尚未配置。在项目终端运行 <code>npm run setup</code>，然后重新启动 <code>npm start</code>。密钥不需要填在网页或聊天中。</div>';return '';}
 function statusBox(){return `${connectionNote()}${error?`<div class="notice" role="alert">${esc(error)}<div class="actions"><button class="secondary" id="retry" ${busy?'disabled':''}>重试本轮分析</button><button class="textbutton" id="choose-rules">切换到规则模式</button></div></div>`:''}${busy?'<div class="notice success" role="status" aria-live="polite">DeepSeek 正在分析当前需求，请稍候。<button class="textbutton" id="cancel">停止等待</button></div>':''}`;}
 function entry(){return `<div class="eyebrow">DEEPSEEK · UNDERSTAND BEFORE BUILDING</div><h1>先把想法，说到一起。</h1><p class="lead">描述你想完成的事。DeepSeek 会找出关键缺口，让你通过选项补充。</p>${statusBox()}<div class="grid"><form class="card" id="ai-start"><label class="input-label" for="ai-intent">你希望 AI 帮你做什么？</label><textarea class="intent-input" id="ai-intent" maxlength="6000" required placeholder="例如：做一个能帮我练雅思口语的网站，但我还没想好要什么功能。">${esc(session.intent)}</textarea><p class="note">点击后，原文会发送给 DeepSeek；后续分析还会包含你的选择。API 使用会产生提供方费用。</p><div class="actions"><span class="hint">不用先选模板或技术框架</span><button class="primary" ${busy||!config.configured?'disabled':''}>让 DeepSeek 梳理 ↗</button></div></form><aside class="side-card"><span class="number">HOW IT WORKS</span><h2>让 AI 先核对理解。</h2><div class="mini-flow"><div><span>01</span> 有依据的信息，交给你确认</div><div><span>02</span> 缺少的关键内容，变成选项</div><div><span>03</span> 再检查遗漏，确认后交接</div></div><p class="note">模型可能误解。它提出候选和追问，最终由你确认范围。一次点选不会自动触发收费调用。</p></aside></div>`;}
 function candidates(){if(!session.candidates.length)return '';return `<section class="facts-panel"><div class="facts-header"><strong>先确认这些理解是否准确</strong><span class="hint">证据引用已检查是否存在；含义是否准确仍由你判断</span></div><ul class="facts-list">${session.candidates.map(c=>{const v=session.decision[c.id]||'pending';return `<li class="fact-item"><div>${badge(v)} <strong>${esc(c.label)}</strong>：${esc(c.value)}</div><div class="evidence">依据 ${esc(c.sourceRef)}：“${esc(c.quote)}”</div><div class="fact-actions"><button class="textbutton" data-ai-fact="${c.id}" data-decision="accepted" ${busy||v==='accepted'?'disabled':''}>${v==='accepted'?'已确认':'这个理解对'}</button><button class="textbutton" data-ai-fact="${c.id}" data-decision="rejected" ${busy||v==='rejected'?'disabled':''}>${v==='rejected'?'已否定':'这个理解不对'}</button></div></li>`;}).join('')}</ul></section>`;}
 function question(q){const a=session.answers[q.id];return `<section class="question" id="ai-question-${q.id}"><h3>${esc(q.title)} ${q.required?'':'<span class="badge">可选</span>'}</h3><p>${esc(q.why)}</p>${a?.status==='stale'?'<div class="notice">关联答案已变化，请重新核对。</div>':''}<div class="options">${q.options.map((o,i)=>`<button class="option ai-option ${a?.status==='confirmed'&&a.value===o.label?'selected':''}" data-ai-answer="${q.id}" data-option="${i}" ${busy?'disabled':''}><span class="radio"></span><span><strong>${esc(o.label)}</strong><small>${esc(o.consequence)}</small></span></button>`).join('')}<button class="option unknown" data-ai-answer="${q.id}" data-special="pending" ${busy?'disabled':''}>暂不确定，继续保留为未知</button></div><form class="custom" data-ai-custom="${q.id}"><input aria-label="${esc(q.title)} 自定义回答" maxlength="2000" placeholder="也可以写自己的想法" value="${esc(drafts[q.id]??'')}" ${busy?'disabled':''}><button ${busy?'disabled':''}>采用</button></form><button class="textbutton not-applicable" data-ai-answer="${q.id}" data-special="excluded" ${busy?'disabled':''}>这个问题不适用（下轮重新评估）</button></section>`;}
 function brief(){return `<aside class="side-card summary"><div class="summary-header"><h3>已经说清楚的部分</h3><span class="number">LIVE BRIEF</span></div><div class="original">${esc(session.intent)}</div>${session.questions.map(q=>{const a=session.answers[q.id];return `<div class="req"><div class="reqtop"><small>${esc(q.id)}</small>${badge(a?.status)}</div><p>${esc(q.title)}</p><p><strong>${esc(a?.value||'尚未回答')}</strong></p><button data-ai-edit="${q.id}" ${busy?'disabled':''}>修改 ↗</button></div>`;}).join('')}<div class="note">本项目已收到 ${session.callCount} 次有效分析。点选先保存在本地，点击“继续分析”才会再次调用。</div></aside>`;}
 function clarify(){if(!batch.length)batch=pendingQs().slice(0,3).map(q=>q.id);const qs=batch.map(id=>session.questions.find(q=>q.id===id)).filter(Boolean);return `<div class="eyebrow">DEEPSEEK · GUIDED CLARIFICATION</div><h1>把关键选择，一起补齐。</h1><p class="lead">选项来自本轮模型分析。你可以选择、补充，也可以纠正它。</p>${statusBox()}${session.analysis?`<div class="ai-understanding"><strong>当前理解</strong><p>${esc(session.analysis.summary)}</p>${session.analysis.signature!==A.signature(session)?'<span class="badge pending">选择已更新，等待重新分析</span>':''}${session.analysis.warnings.map(w=>`<p class="hint">${esc(w)}</p>`).join('')}</div>`:''}${candidates()}<div class="grid"><section class="card">${qs.length?qs.map(question).join(''):'<div class="notice success">当前没有待展示的新问题。核对候选后，可让 DeepSeek 检查是否还有遗漏。</div>'}<div class="actions"><button class="secondary" id="ai-review" ${busy?'disabled':''}>查看需求确认单</button><button class="primary" id="ai-analyze" ${busy||!config.configured?'disabled':''}>继续分析 · 调用 DeepSeek →</button></div><p class="note">每轮最多三个问题。修改后要重新分析，才能使用最新的就绪判断。</p></section>${brief()}</div>`;}
 function review(){const blockers=A.blockers(session),p=A.specification(session);return `<div class="eyebrow">REVIEW THE SHARED BRIEF</div><h1>这份理解，符合你的本意吗？</h1><p class="lead">确认只代表你认可这份需求，不代表任务已经执行或验收。</p>${statusBox()}<div class="grid"><section class="card"><h2>DeepSeek 需求确认单 ${session.activeRevision?'· v'+session.activeRevision:''}</h2><div class="original">${esc(session.intent)}</div><div class="preview"><strong>模型理解（需核对）</strong>${esc(p.summary)}</div>${session.candidates.map(c=>`<section class="review-row"><div class="reqtop">${badge(session.decision[c.id])}<h3>${esc(c.label)}</h3></div><p>${esc(c.value)}</p><small>原文依据：${esc(c.quote)}</small></section>`).join('')}${p.requirements.map(q=>`<section class="review-row"><div class="reqtop">${badge(q.status)}<h3>${esc(q.question)}</h3></div><p>${esc(q.value)}</p><button class="textbutton" data-ai-edit="${q.id}" ${busy?'disabled':''}>修改</button></section>`).join('')}<div class="notice ${blockers.length?'':'success'}">${blockers.length?blockers.map(b=>`<div>${esc(b)}</div>`).join(''):'当前无状态阻塞项。请对照原文核对遗漏，再确认此版本。'}</div><div class="actions"><button class="secondary" id="ai-back" ${busy?'disabled':''}>← 调整与重新分析</button><button class="primary" id="ai-confirm" ${busy||blockers.length||session.activeRevision?'disabled':''}>${session.activeRevision?'已确认 v'+session.activeRevision:'确认这份需求'}</button></div></section><aside class="side-card summary"><span class="number">DEVELOPER HANDOFF</span><h2>让执行有清楚的依据。</h2><p>导出包含原始表达、证据候选、用户选择、未决项与调用信息。</p><div class="actions"><button class="primary" data-ai-export="md">下载 ${session.activeRevision?'确认版':'草稿'} Markdown</button><button class="secondary" data-ai-export="json">下载结构化 JSON</button></div><p class="note">只将已采纳的候选和已确认的回答作为当前范围。否定和不适用项也会保留记录。</p><div class="notice">实现与验收：尚未执行。</div>${session.history.length?`<details class="history"><summary>历史确认版本（${session.history.length}）</summary>${session.history.map((h,i)=>`<button class="secondary" data-ai-history="${i}">下载 v${i+1}</button>`).join('')}</details>`:''}</aside></div>`;}
 function render(){if(!active)return;document.querySelectorAll('[data-ai-custom]').forEach(f=>drafts[f.dataset.aiCustom]=f.querySelector('input').value);$('#main').innerHTML=step===0?entry():step===1?clarify():review();$('.mode').textContent=busy?'DeepSeek · 分析中':session.analysis?'DeepSeek · 已有模型结果':config.configured?'DeepSeek · 密钥已配置':'DeepSeek · 待配置';document.querySelectorAll('[data-step]').forEach(b=>{b.classList.toggle('active',+b.dataset.step===step);b.setAttribute('aria-current',+b.dataset.step===step?'step':'false');b.onclick=()=>{if(busy)return;if(!session.intent&&+b.dataset.step)return;step=+b.dataset.step;render();scrollTo(0,0);};});bind();}
 async function analyze(){if(busy||!config.configured)return;if(session.callCount>=20){error='本任务已分析20轮，请导出当前记录并缩小任务范围后新建。';render();return;}const ticket=++epoch,sig=A.signature(session);controller=new AbortController();busy=true;error='';save();render();try{const r=await fetch('/api/clarify',{method:'POST',headers:{'Content-Type':'application/json','X-IntentConfirm':'1'},body:JSON.stringify(A.input(session)),signal:controller.signal});const body=await r.json();if(!r.ok)throw Error(body.error||'分析失败，请稍后重试。');if(ticket!==epoch)return;session=A.apply(session,body.analysis,body.meta,sig);batch=[];save();}catch(e){if(ticket!==epoch)return;error=e.name==='AbortError'?'已停止等待。本次请求可能已被 DeepSeek 处理，原有需求仍保留。':e.message;}finally{if(ticket===epoch){busy=false;controller=null;render();}}}
 function bind(){
  $('#ai-start')?.addEventListener('submit',async e=>{e.preventDefault();const intent=$('#ai-intent').value.trim();if(!intent)return;if(session.intent!==intent){if(session.intent&&!confirm('新建任务会清除当前本地记录，请先导出需要保留的版本。继续吗？'))return;session=A.fresh(intent);batch=[];drafts={};}step=1;save();await analyze();});
  document.querySelectorAll('[data-ai-fact]').forEach(b=>b.onclick=()=>{try{session=A.decide(session,b.dataset.aiFact,b.dataset.decision);error='';save();render();}catch(e){error=e.message;render();}});
  document.querySelectorAll('[data-ai-answer]').forEach(b=>b.onclick=()=>{const q=session.questions.find(q=>q.id===b.dataset.aiAnswer),status=b.dataset.special||'confirmed',value=status==='pending'?'暂不确定':status==='excluded'?'用户明确标记本题不适用':q.options[+b.dataset.option].label;session=A.answer(session,q.id,value,status);save();render();});
  document.querySelectorAll('[data-ai-custom]').forEach(f=>f.onsubmit=e=>{e.preventDefault();try{session=A.answer(session,f.dataset.aiCustom,f.querySelector('input').value);error='';save();render();}catch(e){error=e.message;render();}});
  document.querySelectorAll('[data-ai-edit]').forEach(b=>b.onclick=()=>{batch=[b.dataset.aiEdit,...pendingQs().map(q=>q.id).filter(id=>id!==b.dataset.aiEdit)].slice(0,3);step=1;render();$('#ai-question-'+b.dataset.aiEdit)?.scrollIntoView({block:'center'});});
  for(const id of ['ai-analyze','retry'])if($('#'+id))$('#'+id).onclick=analyze;
  if($('#cancel'))$('#cancel').onclick=()=>controller?.abort();
  if($('#choose-rules'))$('#choose-rules').onclick=()=>{select.value='rules';select.dispatchEvent(new Event('change'));};
  if($('#ai-review'))$('#ai-review').onclick=()=>{step=2;render();scrollTo(0,0);};
  if($('#ai-back'))$('#ai-back').onclick=()=>{step=1;batch=[];render();scrollTo(0,0);};
  if($('#ai-confirm'))$('#ai-confirm').onclick=()=>{try{session=A.confirm(session);save();render();}catch(e){error=e.message;render();}};
  document.querySelectorAll('[data-ai-export]').forEach(b=>b.onclick=()=>dataDownload(b.dataset.aiExport==='json'?JSON.stringify(A.specification(session),null,2):A.markdown(session),b.dataset.aiExport));
  document.querySelectorAll('[data-ai-history]').forEach(b=>b.onclick=()=>dataDownload(JSON.stringify(session.history[+b.dataset.aiHistory],null,2),'json'));
  $('#reset').onclick=()=>{if(busy)return;if(confirm('清除当前 DeepSeek 项目及本地历史？请先导出需要保留的记录。')){session=A.fresh();step=0;batch=[];drafts={};error='';save();render();}};
 }
 select.addEventListener('change',()=>{active=select.value==='deepseek';if(!active){epoch++;controller?.abort();busy=false;window.IntentOffline.resume();$('.mode').textContent='规则模式 · 未连接模型';}else render();});
 render();
 if(location.protocol==='http:')fetch('/api/status').then(r=>r.ok?r.json():Promise.reject(Error())).then(c=>{config={...c,loaded:true};render();}).catch(()=>{config.loaded=true;error='无法连接本地服务。请确认运行的是 npm start 显示的网址。';render();});
})();
